name: travel_alarm
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.10.8

dependencies:
  flutter:
    sdk: flutter
  # State Management & Storage
  get: ^4.6.6
  get_storage: ^2.1.1
  
  # UI & Utilities
  flutter_screenutil: ^5.9.3
  smooth_page_indicator: ^1.1.0
  cupertino_icons: ^1.0.2
  flutter_svg: ^2.2.3
  
  # Permissions & Location
  permission_handler: ^11.3.0
  geolocator: ^11.0.0
  geocoding: ^3.0.0
  
  # Alarms & Notifications
  flutter_local_notifications: ^17.0.0
  timezone: ^0.9.2
  
  # Date & Time
  intl: ^0.18.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/logos/
